-- MySQL Script generated by MySQL Workbench
-- Sun Apr 10 21:50:58 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group` ;

CREATE TABLE IF NOT EXISTS `Group` (
  `idGroup` INT NOT NULL,
  `Butterflies` TINYINT(1) NULL,
  `Coalas` TINYINT(1) NULL,
  `Minis` TINYINT(1) NULL,
  `Pandas` TINYINT(1) NULL,
  `Roos` TINYINT(1) NULL,
  `SMPants` TINYINT(1) NULL,
  `Tigers` TINYINT(1) NULL,
  `Tinies` TINYINT(1) NULL,
  PRIMARY KEY (`idGroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NICERole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NICERole` ;

CREATE TABLE IF NOT EXISTS `NICERole` (
  `idNICERole` INT NOT NULL,
  `Teacher` TINYINT(1) NULL,
  `Assistent` TINYINT(1) NULL,
  `Substitute` TINYINT(1) NULL,
  `Student` TINYINT(1) NULL,
  `Group` INT NULL,
  PRIMARY KEY (`idNICERole`),
  CONSTRAINT `Group`
    FOREIGN KEY (`Group`)
    REFERENCES `Group` (`idGroup`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `Group_idx` ON `NICERole` (`Group` ASC);


-- -----------------------------------------------------
-- Table `Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Administrator` ;

CREATE TABLE IF NOT EXISTS `Administrator` (
  `idAdministrator` INT NOT NULL,
  `Role` ENUM('Group Chair', 'Membership', 'Teacher Recruitment', 'Finance', 'Special Events') NULL,
  PRIMARY KEY (`idAdministrator`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Address` ;

CREATE TABLE IF NOT EXISTS `Address` (
  `idAddress` INT NOT NULL,
  `Street` VARCHAR(45) NULL,
  `ZipCode` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Telephone` VARCHAR(45) NULL,
  `Mobile` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Person` ;

CREATE TABLE IF NOT EXISTS `Person` (
  `idPerson` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Nickname` VARCHAR(45) NULL,
  `BDay` DATE NOT NULL,
  `Child` TINYINT(1) NOT NULL,
  `NICERole` INT NULL,
  `Administrator` INT NULL,
  `Nationality` VARCHAR(45) NULL,
  `DistributionListConsent` TINYINT(1) NOT NULL DEFAULT 0,
  `PictureConsent` TINYINT(1) NOT NULL DEFAULT 0,
  `Address` INT NULL,
  `Occupation` VARCHAR(45) NULL,
  `Activity` VARCHAR(45) NULL,
  PRIMARY KEY (`idPerson`),
  CONSTRAINT `NICERole`
    FOREIGN KEY (`NICERole`)
    REFERENCES `NICERole` (`idNICERole`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Administrator`
    FOREIGN KEY (`Administrator`)
    REFERENCES `Administrator` (`idAdministrator`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Address`
    FOREIGN KEY (`Address`)
    REFERENCES `Address` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `NICERole_idx` ON `Person` (`NICERole` ASC);

CREATE INDEX `Administrator_idx` ON `Person` (`Administrator` ASC);

CREATE INDEX `Address_idx` ON `Person` (`Address` ASC);


-- -----------------------------------------------------
-- Table `Membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Membership` ;

CREATE TABLE IF NOT EXISTS `Membership` (
  `idRegistrationInf` INT NOT NULL,
  `Referral` VARCHAR(45) NULL,
  `GermanySince` DATE NULL,
  `SpokenLanguages` VARCHAR(45) NULL,
  `Status` ENUM('active', 'inactive', 'visitor', 'exvisitor', 'interessted', 'honorary') NULL,
  `FirstContact` DATE NULL,
  `FirstVisitedDate` DATE NULL,
  `RegistrationDate` DATE NULL,
  `InactiveDate` DATE NULL,
  PRIMARY KEY (`idRegistrationInf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Family` ;

CREATE TABLE IF NOT EXISTS `Family` (
  `idFamily` INT NOT NULL,
  `Mother` INT NULL,
  `Father` INT NULL,
  `Child` INT NULL,
  `Membership` INT NULL,
  PRIMARY KEY (`idFamily`),
  CONSTRAINT `Mother`
    FOREIGN KEY (`Mother`)
    REFERENCES `Person` (`idPerson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Father`
    FOREIGN KEY (`Father`)
    REFERENCES `Person` (`idPerson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Child`
    FOREIGN KEY (`Child`)
    REFERENCES `Person` (`idPerson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Membership`
    FOREIGN KEY (`Membership`)
    REFERENCES `Membership` (`idRegistrationInf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `Mother_idx` ON `Family` (`Mother` ASC);

CREATE INDEX `Father_idx` ON `Family` (`Father` ASC);

CREATE INDEX `Child_idx` ON `Family` (`Child` ASC);

CREATE INDEX `Membership_idx` ON `Family` (`Membership` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
